### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by gedw99** [whitaker-io/machine#105]
**Is your feature request related to a problem? Please describe.**

Love the architecture but its currently all library based and was hoping for an example so i can try it out and see if its a good fit.

**Describe the solution you'd like**
A repo with an example Or just an example in this repo...

thanks again @jonathan-whitaker for this project.

**Comment by jonathan-whitaker** [comment]
Sure, I'm currently working on the generics version for go 1.18. but i will put something together. Do you plan on needing it to fan out? If so i can do an example with either GCP Pub/Sub or AWS SQS, I'll do both eventually, but wanna know what to prioritize.

**Comment by gedw99** [comment]
Hey @jonathan-whitaker 

thank you very much for responding. 

Fan out is needed. But in the interests of not boiling the ocean, can do without it for initial example.

I generally use NATS, but for now GCP PUB SUB is great.
